### ISSUE TITLE
Deploy as AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [mxklb/cuteproject#14]
Deploying Linux binaries as in the [AppImage](http://appimage.org/) format would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

The [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) tool can be easily integrated with Travis CI to produce AppImages of Qt applications.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by probonopd** [comment]
Please let me know once the AppImage is available on https://github.com/mxklb/cuteproject/releases so that I can include it in the AppImageHub central directory of available AppImages.

**Comment by mxklb** [comment]
@probonopd when I work on the versioning issue #9 I'll introduce github releases.

I will let you know when this is done, so you can include it in the AppImageHub, thank you very much!
